/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.4.1.213 */
/* Module Version: 1.2 */
/* Wed Nov 04 16:19:06 2015 */

/* parameterized module instance */
spi_slave_efb1300E __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), 
    .wb_stb_i( ), .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), 
    .wb_ack_o( ), .spi_clk( ), .spi_miso( ), .spi_mosi( ), .spi_scsn( ), 
    .spi_irq( ));
